Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "hashicorp/trusty64"
  c.vm.hostname = "default-hashicorp-trusty64.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-install_pkg-default-hashicorp-trusty64"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
