Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "ubuntu/trusty64"
  c.vm.hostname = "default-ubuntu-trusty64.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-createdir-ec2-default-ubuntu-trusty64"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
